# docker-compose.yml
version: '3.8'

services:
  autogenstudio:
    build:
      context: .
      dockerfile: Dockerfile
    image: autogenstudio:latest
    restart: unless-stopped
    environment:
      # Matches the ENV in your Dockerfile
      AUTOGENSTUDIO_APPDIR: /home/user/app
    volumes:
      # Mount your local code into the container for easy updates
      - .:/home/user/app:delegated
    ports:
      - "8081:8081"
    # Use the same command as in your Dockerfile’s CMD
    command: >
      sh -c "gunicorn -w $((2 * \$(getconf _NPROCESSORS_ONLN) + 1))
      --timeout 12600
      -k uvicorn.workers.UvicornWorker
      autogenstudio.web.app:app
      --bind 0.0.0.0:8081"